#!/usr/bin/env node
const fse = require("fs-extra");
/* Fetch tools */
const fetch = require("node-fetch");
/* CLI Dependencies */
// const Spinner = require("cli-spinner").Spinner;
const chalk = require("chalk");
const clear = require("clear");
const styles = require("../styles/chalkStyle");
/* Klara's utility functions */
const filesIterator = require("./utils/filesIterator.js");
const filesDownloader = require("./utils/filesDownloader.js");
const spinner = require("./utils/spinner");
/* Config generated by CLI tool */
const CONFIG = require(`${process.cwd()}/icons.config.js`);

module.exports = function assetsDownloader() {
  const url = CONFIG.url; // UXPin DS data URL set in the config file
  /* Clear terminal */
  clear();

  /* Show Klara welcome message */
  const titleChalk = text => styles.text.titleChalk(text);
  console.log(
    titleChalk("Klara. Assets and Icons Management for UXPin Design Systems.")
  );

  /* Set loader/spinner */
  const spin = spinner("Thinking...");
  spin.setSpinnerString(27);
  spin.start();

  /* Fetch JSON from UXPin servers */
  (function() {
    return fetch(url)
      .then(response => {
        return response.json();
      })
      .then(json => json.find((obj, i) => obj.type === "assets"))
      .then(assets => {
        return assets.categories.map(item => filesIterator(item));
      })
      .then(data => {
        return data.map(elem =>
          filesDownloader(elem.categoryDir, elem.assetsArr)
        );
      })
      .then(() => {
        spin.stop(true);
        return;
      });
  })();
};
